version: "2"
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        links:
            - db
        ports:
            - "5000:5000"
    db:
        image: mysql:5.7
        ports:
            - "32000:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: "features"
            MYSQL_USER: "newUser"
            MYSQL_PASSWORD: "emerald976"
        volumes:
            - ./db:/docker-entrypoint-initdb.d/:ro